### ISSUE TITLE
n

### ISSUE THREAD

**Issue by jamienjoroge** [devc-nairobi/ntw-hello-bot#4]
Hey Was wondering if after the user interacts and gives the permission to allow the bot to conversate could the bot still message the user regularly without the user actually engaging with the bot

**Comment by Benedict-Mambo** [comment]
Businesses and developers using the Send/Receive API have up to 24 hours to respond to a message initiated by a person in Messenger when using standard messaging. There is also an allowance to send one message after the 24 hour window.

So, your messeges have to be on an interaction basis, and only one message on allowance.

Maybe Nandaa can help more on this.

**Comment by profnandaa** [comment]
GQ! Moved your Q here so that everyone gains - https://github.com/devcnairobi/ntw-hello-bot/issues/1#issuecomment-382768914
